// Datos que simulan las respuestas del backend momentaneamente
// Estructura basada en CourseSummaryResponse y CourseDetailResponse

export const MOCK_COURSES = [
  {
    id: 'uuid-course-001',
    title: 'Desarrollo Web con React',
    description: 'Aprende React desde cero hasta nivel avanzado. Hooks, Context, React Router y más.',
    instructorName: 'Carlos Instructor',
    price: 29.99,
    rating: 4.8,
    totalStudents: 1240,
    durationHours: 24,
    category: 'PROGRAMACION',
    thumbnailUrl: 'https://placehold.co/400x225/3b82f6/ffffff?text=React',
    isPublished: true,
    totalLessons: 48,
  },
  {
    id: 'uuid-course-002',
    title: 'Java Spring Boot — API REST',
    description: 'Construye APIs profesionales con Spring Boot, JPA, Spring Security y JWT.',
    instructorName: 'María González',
    price: 34.99,
    rating: 4.9,
    totalStudents: 980,
    durationHours: 30,
    category: 'PROGRAMACION',
    thumbnailUrl: 'https://placehold.co/400x225/16a34a/ffffff?text=Spring+Boot',
    isPublished: true,
    totalLessons: 55,
  },
  {
    id: 'uuid-course-003',
    title: 'Diseño UX/UI con Figma',
    description: 'Domina Figma y aprende los principios de diseño de interfaces modernas.',
    instructorName: 'Sofía Ramírez',
    price: 24.99,
    rating: 4.7,
    totalStudents: 760,
    durationHours: 18,
    category: 'DISENO',
    thumbnailUrl: 'https://placehold.co/400x225/9333ea/ffffff?text=Figma',
    isPublished: true,
    totalLessons: 36,
  },
  {
    id: 'uuid-course-004',
    title: 'Python para Data Science',
    description: 'Pandas, NumPy, visualización de datos y machine learning con Python.',
    instructorName: 'Luis Martínez',
    price: 39.99,
    rating: 4.6,
    totalStudents: 1540,
    durationHours: 36,
    category: 'DATA',
    thumbnailUrl: 'https://placehold.co/400x225/f59e0b/ffffff?text=Python',
    isPublished: true,
    totalLessons: 72,
  },
  {
    id: 'uuid-course-005',
    title: 'Marketing Digital',
    description: 'SEO, redes sociales, email marketing y estrategias de crecimiento.',
    instructorName: 'Andrea López',
    price: 19.99,
    rating: 4.5,
    totalStudents: 2100,
    durationHours: 15,
    category: 'MARKETING',
    thumbnailUrl: 'https://placehold.co/400x225/ef4444/ffffff?text=Marketing',
    isPublished: true,
    totalLessons: 30,
  },
  {
    id: 'uuid-course-006',
    title: 'Node.js y Express',
    description: 'Backend con JavaScript: APIs REST, autenticación, bases de datos.',
    instructorName: 'Carlos Instructor',
    price: 29.99,
    rating: 4.7,
    totalStudents: 890,
    durationHours: 22,
    category: 'PROGRAMACION',
    thumbnailUrl: 'https://placehold.co/400x225/0f766e/ffffff?text=Node.js',
    isPublished: true,
    totalLessons: 44,
  },
];

export const MOCK_COURSE_DETAIL = {
  'uuid-course-001': {
    id: 'uuid-course-001',
    title: 'Desarrollo Web con React',
    description: 'Aprende React desde cero hasta nivel avanzado. Hooks, Context, React Router y más. Este curso cubre todo lo que necesitas para construir aplicaciones web modernas y profesionales.',
    instructorName: 'Carlos Instructor',
    instructorId: 'uuid-instructor-001',
    price: 29.99,
    rating: 4.8,
    totalStudents: 1240,
    durationHours: 24,
    category: 'PROGRAMACION',
    thumbnailUrl: 'https://placehold.co/800x450/3b82f6/ffffff?text=React',
    isPublished: true,
    modules: [
      {
        id: 'uuid-module-001',
        title: 'Fundamentos de React',
        orderIndex: 1,
        lessons: [
          { id: 'uuid-lesson-001', title: '¿Qué es React?', contentType: 'VIDEO', durationMinutes: 12, orderIndex: 1, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
          { id: 'uuid-lesson-002', title: 'Componentes y Props', contentType: 'VIDEO', durationMinutes: 18, orderIndex: 2, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
          { id: 'uuid-lesson-003', title: 'Estado con useState', contentType: 'VIDEO', durationMinutes: 22, orderIndex: 3, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
        ],
      },
      {
        id: 'uuid-module-002',
        title: 'Hooks Avanzados',
        orderIndex: 2,
        lessons: [
          { id: 'uuid-lesson-004', title: 'useEffect en profundidad', contentType: 'VIDEO', durationMinutes: 25, orderIndex: 1, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
          { id: 'uuid-lesson-005', title: 'useContext y estado global', contentType: 'VIDEO', durationMinutes: 20, orderIndex: 2, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
          { id: 'uuid-lesson-006', title: 'Custom Hooks', contentType: 'PDF', durationMinutes: 15, orderIndex: 3, contentUrl: 'https://react.dev' },
        ],
      },
      {
        id: 'uuid-module-003',
        title: 'React Router',
        orderIndex: 3,
        lessons: [
          { id: 'uuid-lesson-007', title: 'Rutas básicas', contentType: 'VIDEO', durationMinutes: 18, orderIndex: 1, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
          { id: 'uuid-lesson-008', title: 'Rutas protegidas', contentType: 'VIDEO', durationMinutes: 22, orderIndex: 2, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
        ],
      },
    ],
  },

  'uuid-course-002': {
    id: 'uuid-course-002',
    title: 'Java Spring Boot — API REST',
    description: 'Construye APIs profesionales con Spring Boot, JPA, Spring Security y JWT. Aprenderás a diseñar arquitecturas limpias con N-Capas y despliegue en la nube.',
    instructorName: 'María González',
    instructorId: 'uuid-instructor-002',
    price: 34.99,
    rating: 4.9,
    totalStudents: 980,
    durationHours: 30,
    category: 'PROGRAMACION',
    thumbnailUrl: 'https://placehold.co/800x450/16a34a/ffffff?text=Spring+Boot',
    isPublished: true,
    modules: [
      {
        id: 'uuid-module-004',
        title: 'Introducción a Spring Boot',
        orderIndex: 1,
        lessons: [
          { id: 'uuid-lesson-009', title: 'Configuración del proyecto', contentType: 'VIDEO', durationMinutes: 15, orderIndex: 1, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
          { id: 'uuid-lesson-010', title: 'Estructura N-Capas', contentType: 'VIDEO', durationMinutes: 20, orderIndex: 2, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
        ],
      },
      {
        id: 'uuid-module-005',
        title: 'Spring Security y JWT',
        orderIndex: 2,
        lessons: [
          { id: 'uuid-lesson-011', title: 'Configurando Spring Security', contentType: 'VIDEO', durationMinutes: 28, orderIndex: 1, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
          { id: 'uuid-lesson-012', title: 'Generando tokens JWT', contentType: 'VIDEO', durationMinutes: 22, orderIndex: 2, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
          { id: 'uuid-lesson-013', title: 'Protegiendo endpoints', contentType: 'PDF', durationMinutes: 18, orderIndex: 3, contentUrl: 'https://spring.io' },
        ],
      },
    ],
  },

  'uuid-course-003': {
    id: 'uuid-course-003',
    title: 'Diseño UX/UI con Figma',
    description: 'Domina Figma y aprende los principios de diseño de interfaces modernas. Desde wireframes hasta prototipos interactivos y handoff para desarrolladores.',
    instructorName: 'Sofía Ramírez',
    instructorId: 'uuid-instructor-003',
    price: 24.99,
    rating: 4.7,
    totalStudents: 760,
    durationHours: 18,
    category: 'DISENO',
    thumbnailUrl: 'https://placehold.co/800x450/9333ea/ffffff?text=Figma',
    isPublished: true,
    modules: [
      {
        id: 'uuid-module-006',
        title: 'Fundamentos de UX',
        orderIndex: 1,
        lessons: [
          { id: 'uuid-lesson-014', title: 'Qué es UX y por qué importa', contentType: 'VIDEO', durationMinutes: 14, orderIndex: 1, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
          { id: 'uuid-lesson-015', title: 'Research y entrevistas de usuario', contentType: 'VIDEO', durationMinutes: 20, orderIndex: 2, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
        ],
      },
      {
        id: 'uuid-module-007',
        title: 'Figma desde cero',
        orderIndex: 2,
        lessons: [
          { id: 'uuid-lesson-016', title: 'Interfaz y herramientas de Figma', contentType: 'VIDEO', durationMinutes: 18, orderIndex: 1, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
          { id: 'uuid-lesson-017', title: 'Componentes y Auto Layout', contentType: 'VIDEO', durationMinutes: 25, orderIndex: 2, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
          { id: 'uuid-lesson-018', title: 'Prototipado interactivo', contentType: 'VIDEO', durationMinutes: 22, orderIndex: 3, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
        ],
      },
    ],
  },

  'uuid-course-004': {
    id: 'uuid-course-004',
    title: 'Python para Data Science',
    description: 'Pandas, NumPy, visualización de datos y machine learning con Python. Aprenderás a limpiar datos, crear modelos predictivos y comunicar hallazgos con visualizaciones profesionales.',
    instructorName: 'Luis Martínez',
    instructorId: 'uuid-instructor-004',
    price: 39.99,
    rating: 4.6,
    totalStudents: 1540,
    durationHours: 36,
    category: 'DATA',
    thumbnailUrl: 'https://placehold.co/800x450/f59e0b/ffffff?text=Python',
    isPublished: true,
    modules: [
      {
        id: 'uuid-module-008',
        title: 'Python para análisis de datos',
        orderIndex: 1,
        lessons: [
          { id: 'uuid-lesson-019', title: 'Numpy y arrays', contentType: 'VIDEO', durationMinutes: 20, orderIndex: 1, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
          { id: 'uuid-lesson-020', title: 'Pandas: DataFrames', contentType: 'VIDEO', durationMinutes: 30, orderIndex: 2, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
          { id: 'uuid-lesson-021', title: 'Limpieza de datos', contentType: 'PDF', durationMinutes: 18, orderIndex: 3, contentUrl: 'https://pandas.pydata.org' },
        ],
      },
      {
        id: 'uuid-module-009',
        title: 'Visualización',
        orderIndex: 2,
        lessons: [
          { id: 'uuid-lesson-022', title: 'Matplotlib y Seaborn', contentType: 'VIDEO', durationMinutes: 25, orderIndex: 1, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
          { id: 'uuid-lesson-023', title: 'Dashboards con Plotly', contentType: 'VIDEO', durationMinutes: 28, orderIndex: 2, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
        ],
      },
    ],
  },

  'uuid-course-005': {
    id: 'uuid-course-005',
    title: 'Marketing Digital',
    description: 'SEO, redes sociales, email marketing y estrategias de crecimiento. Aprende a crear campañas que conviertan y medir resultados con datos reales.',
    instructorName: 'Andrea López',
    instructorId: 'uuid-instructor-005',
    price: 19.99,
    rating: 4.5,
    totalStudents: 2100,
    durationHours: 15,
    category: 'MARKETING',
    thumbnailUrl: 'https://placehold.co/800x450/ef4444/ffffff?text=Marketing',
    isPublished: true,
    modules: [
      {
        id: 'uuid-module-010',
        title: 'SEO y posicionamiento',
        orderIndex: 1,
        lessons: [
          { id: 'uuid-lesson-024', title: 'Cómo funciona Google', contentType: 'VIDEO', durationMinutes: 16, orderIndex: 1, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
          { id: 'uuid-lesson-025', title: 'Investigación de palabras clave', contentType: 'VIDEO', durationMinutes: 22, orderIndex: 2, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
        ],
      },
      {
        id: 'uuid-module-011',
        title: 'Redes sociales',
        orderIndex: 2,
        lessons: [
          { id: 'uuid-lesson-026', title: 'Estrategia de contenido', contentType: 'VIDEO', durationMinutes: 18, orderIndex: 1, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
          { id: 'uuid-lesson-027', title: 'Publicidad pagada', contentType: 'VIDEO', durationMinutes: 24, orderIndex: 2, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
        ],
      },
    ],
  },

  'uuid-course-006': {
    id: 'uuid-course-006',
    title: 'Node.js y Express',
    description: 'Backend con JavaScript: APIs REST, autenticación, bases de datos. Aprenderás a construir servidores escalables y conectarlos a bases de datos relacionales y no relacionales.',
    instructorName: 'Carlos Instructor',
    instructorId: 'uuid-instructor-001',
    price: 29.99,
    rating: 4.7,
    totalStudents: 890,
    durationHours: 22,
    category: 'PROGRAMACION',
    thumbnailUrl: 'https://placehold.co/800x450/0f766e/ffffff?text=Node.js',
    isPublished: true,
    modules: [
      {
        id: 'uuid-module-012',
        title: 'Node.js fundamentos',
        orderIndex: 1,
        lessons: [
          { id: 'uuid-lesson-028', title: 'Event loop y asincronía', contentType: 'VIDEO', durationMinutes: 20, orderIndex: 1, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
          { id: 'uuid-lesson-029', title: 'Módulos y NPM', contentType: 'VIDEO', durationMinutes: 15, orderIndex: 2, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
        ],
      },
      {
        id: 'uuid-module-013',
        title: 'Express y APIs REST',
        orderIndex: 2,
        lessons: [
          { id: 'uuid-lesson-030', title: 'Creando tu primer servidor', contentType: 'VIDEO', durationMinutes: 18, orderIndex: 1, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
          { id: 'uuid-lesson-031', title: 'Middlewares', contentType: 'VIDEO', durationMinutes: 22, orderIndex: 2, contentUrl: 'https://www.youtube.com/embed/dGcsHMXbSOA' },
          { id: 'uuid-lesson-032', title: 'Autenticación con JWT', contentType: 'PDF', durationMinutes: 20, orderIndex: 3, contentUrl: 'https://expressjs.com' },
        ],
      },
    ],
  },
};

export const MOCK_CATEGORIES = [
  { value: '', label: 'Todas las categorías' },
  { value: 'Programación', label: 'Programación' },
  { value: 'Diseño', label: 'Diseño' },
  { value: 'Data Science', label: 'Data Science' },
  { value: 'Marketing', label: 'Marketing' },
];